# File: seeds.rb
#
# You can run this many ways, here are some commands:
# 1 run: rails db:drop
# 2 run: rails db:setup (will run migrations & seed file)
# 3 run: rails db:seed
#
# This ensures that the first User id created for User will be "1"
# Then we can add libations, need to have user_id=1
# First Libation record has a "create-bang" to if something craps, we'll see a message.

User.delete_all
u = User.new
u.email = 'rob@rtfm.ca'
u.encrypted_password = "$2a$11$n2DRki7QLOhuVcSjC882A.Um5UNXcM4X6pxG.yNPz.T4RvxwDypAe"
u.save(validate: false)

puts "Need user created with id=1. We created it = #{User.first.id}."

Libation.delete_all
Libation.create!(libation_name: "Milkis Orange milk",             libation_type: "Soda",   website: "www.lottechilsong.co.uk",        country_made: "Korea",          company_name: "Lotte"               ,   container_type: "Steel"    ,  weight: 238,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "light orange",       carbonated: 0, store_purchased: "Daiai",                  pulp: 4,  can_art:4, can_design:4,  sweet:3,  flavour:4,  sip_guzz:4,  juice:0,  buy_again: "Yes",      date_drank: "2006-09-15",  image: "milkis.orange",  comments: "Liked squirty pieces of pulp", user_id:1)
Libation.create(libation_name: "Melon soda",                     libation_type: "Soda",   website: "info@sangariausa.com",           country_made: "Japan",          company_name: "Sangaria"            ,   container_type: "Aluminium",  weight: 480,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "opaque green",       carbonated: 0, store_purchased: "Daiai",                  pulp: 0,  can_art:5, can_design:4,  sweet:4,  flavour:1,  sip_guzz:2,  juice:0,  buy_again: "Maybe",    date_drank: "2006-09-13",  image: "Sangaria.melon",  comments: "Loved the feel of the container" , user_id:1)
Libation.create(libation_name: "Strawberry soda",                libation_type: "Soda",   website: "info@sangariausa.com",           country_made: "Japan",          company_name: "Sangaria"            ,   container_type: "Aluminium",  weight: 480,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "opaque pink",        carbonated: 0, store_purchased: "Daiai",                  pulp: 0,  can_art:5, can_design:4,  sweet:4,  flavour:1,  sip_guzz:2,  juice:0,  buy_again: "Maybe",    date_drank: "2006-09-17",  image: "Sangaria.strawberry",  comments: "Loved the feel of the container" , user_id:1)
Libation.create(libation_name: "Aloe vera bits &amp; grape Juice",libation_type: "Juice", website: nil,                              country_made: "Japan",          company_name: "Pokka"               ,   container_type: "Aluminium",  weight: 300,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "clear",              carbonated: 0, store_purchased: "Daiai",                  pulp: 4,  can_art:3, can_design:1,  sweet:3,  flavour:5,  sip_guzz:3,  juice:0,  buy_again: "Yes",      date_drank: "2006-08-23", image: "pokka.grape",  comments: "Cannot guzzle this as the aloe bits are large!" , user_id:1)
Libation.create(libation_name: "Aloe vera bits &amp; apple Juice",libation_type: "Juice", website: nil,                              country_made: "Japan",          company_name: "Pokka"               ,   container_type: "Aluminium",  weight: 300,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "clear",              carbonated: 0, store_purchased: "Daiai",                  pulp: 4,  can_art:3, can_design:1,  sweet:3,  flavour:2,  sip_guzz:3,  juice:0,  buy_again: "No",       date_drank: "2006-09-03", image: "pokka.apple",  comments: "Red apple did not go well." , user_id:1)
Libation.create(libation_name: "Aloe vera bits &amp; peach Juice",libation_type: "Juice", website: nil,                              country_made: "Japan",          company_name: "Pokka"               ,   container_type: "Aluminium",  weight: 300,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "clear",              carbonated: 0, store_purchased: "Daiai",                  pulp: 4,  can_art:3, can_design:1,  sweet:3,  flavour:4,  sip_guzz:3,  juice:0,  buy_again: "Yes",      date_drank: "2006-09-03", image: nil, comments: "Some aloe bits got stuck in can!" , user_id:1)
Libation.create(libation_name: "Calpico Strawberry Drink",       libation_type: "Drink",  website: nil,                              country_made: "Japan",          company_name: "Calpis"              ,   container_type: "Plastic"  ,  weight: 500,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "yellow",             carbonated: 0, store_purchased: "Daiai",                  pulp: 0,  can_art:3, can_design:2,  sweet:2,  flavour:3,  sip_guzz:3,  juice:1,  buy_again: "Yes",      date_drank: "2006-09-23",  image: "Calpico.strawberry",  comments: "Kinda tasty might change my mind after a few." , user_id:1)
Libation.create(libation_name: "Watermelon",                     libation_type: "Drink",  website: nil,                              country_made: "USA",            company_name: "Arizona"             ,   container_type: "Glass"    ,  weight: 473,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "light red",          carbonated: 0, store_purchased: "Daiai",                  pulp: 0,  can_art:4, can_design:4,  sweet:4,  flavour:3,  sip_guzz:4,  juice:10,  buy_again: "Yes",     date_drank: "2006-09-11",  image: "Arizona.watermelon.b",  comments: "Good for a guzzle." , user_id:1)
Libation.create(libation_name: "Calpico Mango Drink",            libation_type: "Drink",  website: nil,                              country_made: "Japan",          company_name: "Calpis"              ,   container_type: "Plastic"  ,  weight: 500,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "yellow",             carbonated: 0, store_purchased: "Daiai",                  pulp: 0,  can_art:3, can_design:2,  sweet:2,  flavour:3,  sip_guzz:3,  juice:1,  buy_again: "Yes",      date_drank: "2006-11-01",  image: "calpico.mango",  comments: "Milk based. Not bad for a 1% juice." , user_id:1)
Libation.create(libation_name: "Chrysanthemum Tea Drink",        libation_type: "Tea",    website: "www.chiaokuo.com",               country_made: "Taiwan",         company_name: "Chiao Kuo"           ,   container_type: "Steel"    ,  weight: 350,   weight_type: "millilitres" , city_purchased: "Honolulu",      prov_purchased: "Hi",  country_purchased: "USA",    colour: "clear",              carbonated: 0, store_purchased: "Daiai",                  pulp: 0,  can_art:4, can_design:1,  sweet:2,  flavour:5,  sip_guzz:0,  juice:0,  buy_again: "Yes",      date_drank: "2006-10-22",  image: "chiao.chry",  comments: "Really flavourfull" , user_id:1)
puts "Fini..."
